linters-settings:
  goimports:
    # Separate internal packages from external
    local-prefixes: github.com/"github.com/daveseco7/advent-of-code-2021

linters:
  # Enable extra linters besides the default ones
  enable:
    - goimports
    - godot
    - goconst
    - gofumpt
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - bodyclose

issues:
  exclude-rules:
    - path: /
      linters:
        - stylecheck
      text: "ST1003:"